### ISSUE TITLE
docker build command in Linux - docker_cli.sh 

### ISSUE THREAD

**Issue by nmorandeira** [rsangole/user2022-r-for-docker#9]
**Describe the bug**
To build the docker image in Linux, a space is needed before this last period:

`docker build --file Dockerfile -t docker_for_r/simple:test .`

File: [docker_cli.sh](https://github.com/rsangole/user2022-r-for-docker/blob/main/03-docker-cli/docker-cli.sh)

**Comment by rsangole** [comment]
Yep, you're right, thanks!
